# Port Configuration
server:
  port: 8080

# Database Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/BLOG_DB
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true

  # Multipart Configuration
  servlet:
    multipart:
      file-size-threshold: 128KB
      max-file-size: 128MB
      max-request-size: 128MB

  # log Configuration

#  flyway:
#    loggers: true
#logging:
#  level:
#    web: debug
#    org.hibernate: debug






